### ISSUE TITLE
roll 0.5.2

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/core-elements#176]
Originally filed at: https://code.google.com/p/dart/issues/detail?id=21953 by by vittorio.ballestra:
> Subject: core-selector on FF (33+) on linux doesn't work
 Could you please upgrade polymer to 0.5.2 at least ? 
 This bug is resolved in 0.5.2 and is driving me crazy:
 https://github.com/Polymer/polymer-gestures/issues/77
 Tnx.

**Comment by fedy2** [comment]
I've open an issue for 0.5.4 #188,  maybe this one can be closed.
