### ISSUE TITLE
Using the CoreList in a hidden container requires to call the updateSize method

### ISSUE THREAD

**Issue by fedy2** [dart-lang/core-elements#183]
I'm using the last `CoreList` version in a container that is hidden at start-up time. When then I visualize it the list panel is blank. You can reproduce the behavior modifying the basic example:
* hide the list with the `display` CSS attribute set to `none` 
* set it to `block` again using a button.

I've read the `CoreList` source code and I've found the `updateSize` method. The method's comment says that you have to call it when the list is resized or visualized after been hidden. I've modified the basic example again in order to call the method when I make the list visible and the list is now visualized correctly.

Do you confirm that we need to call such method after the list is visualized?
Do you any way to get aware about list visibility?
The only way I can think about is to propagate from parent to child the visibility state, but this is a little tricky.

This is more a request of confirm than an issue, sorry if I've posted it in the wrong place.

**Comment by jakemac53** [comment]
Yes, you do have to call updateSize after changing the containers size in general. It uses the height to determine how many items it should render, and when the height computes to 0 it will not render anything. I don't know of a way to detect when the visibility or height changes (other than polling or something along those lines).

**Comment by jakemac53** [comment]
If you are ok with it still affecting layout but just being invisible, then setting visibility: hidden should work and it will still have a height > 0.

**Comment by fedy2** [comment]
You're right, using the visibility attribute the height is available and the number of rows to render calculate right. 
The core-pages uses this attribute and the list works fine.
My problem is that due to https://github.com/dart-lang/core-elements/issues/128 I have to use the core-animated-pages element which uses the display attribute.

**Comment by Andersmholmgren** [comment]
Glad to see someone mentioning core-list and core-animated-pages as that combination is behaving very poorly for me. Rather than hijack this issue though, I'll create another one and link them

**Comment by fedy2** [comment]
I've experimented with the visibility attribute but when I hide the list it keeps his space occupied.
The core-list in Polymer "implements" Polymer.CoreResizable in order to propagate size between parent (CoreResizer) and children (CoreResizable). 
There is a similar/same mechanism in core-elements dart?

**Comment by jakemac53** [comment]
It looks like this was added in a more recent version than we have currently ported. When we do the next roll, this should come along with it.

**Comment by fedy2** [comment]
OK, open a ticket for 0.5.4 rollout #188.
