### ISSUE TITLE
core-list-dart doesn't display items when inside core-pages (core-animated-pages)

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/core-elements#186]
see http://stackoverflow.com/questions/27736325/how-to-use-core-scroll-header-panel-with-core-animated-pages/27750389#27750389

I imagine that this is because core-list suffers from such issues, as I believe core-list-dart is implemented to track it feature wise. See http://stackoverflow.com/questions/27736325/how-to-use-core-scroll-header-panel-with-core-animated-pages/27750389#27750389

Manually resizing the browser window always gets it to display correctly, but not otherwise. 

I have several tabs that have their own core-list-dart in them. When switching tabs etc it's often just a row or two that renders (until I resize the browser window manually).

**Comment by jakemac53** [comment]
I would recommend filing this on the main repo here https://github.com/polymer/core-list. Any changes made there will make their way here. As far as I know this this is working as designed.

**Comment by Andersmholmgren** [comment]
I think there is more at play here. I do the following

1. switch the selected page in core-animated-pages to a page that displays a core-list. The list is blank (presumably as I need to call updateSize).
1. I resize the window and the list is correctly displayed with 10 rows
1. I switch to another page and do an operation that removes one item from the list backing the core-list in the previous page
1. I switch back to the page with the core-list. Instead of seeing 9 rows I see just 1 row - the last one
1. I resize the window and can see all 9 rows

So this seems to be something more than just the need to call updateSize. Surely I don't need to call updateSize every time the data that backs the list changes size as polymer surely can detect the observable event.

**Comment by Andersmholmgren** [comment]
OK I have a hack around for this that seems to be working for these cases but pretty hideous efficiency wise so will need to find something cleaner.

What I do is listen for the tab selection property change and then do

```
final l = []..addAll(myObservableList);
myObservableList.clear();
new Future(() {
  myObservableList.addAll(l);
});
```

I'll see if I can hook it up to do coreList.updateSize instead but that is more painful for me as all my logic is in viewModels that only depend on observe, not polymer

**Comment by Andersmholmgren** [comment]
Sorry for the spam ...

Got a new hack working that uses updateSize instead. I added a property (`listDirtied`) on my view model (`editor`). It's just and int that I increment to trigger and observe event when ever the containing page is displayed. Then I do

```
      onPropertyChange(editor, #listDirtied, () {
        new Future( () {
          coreList.updateSize();
        });
      });
```

This seems to work and I will go with that but I truly hope that the need for such hackery is not 'by design'

**Comment by Andersmholmgren** [comment]
See https://github.com/Polymer/polymer/issues/849

**Comment by Andersmholmgren** [comment]
This was due to a combination of not calling updateSize and not setting the scrollTarget
