### ISSUE TITLE
core-pages always showing google maps

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/core-elements#194]
core-pages is always showing google maps no matter which page is selected, even though google maps is in a different polymer component.  It's switching pages correctly as the correct core-toolbar is showing, but google maps is always visible.

```
<core-pages id="pages" selected="0" flex>
    <home-view></home-view>
    <map-view></map-view> <!-- contains google map -->
</core-pages>
```

**Comment by jakemac53** [comment]
It looks like we will need a bit more info here, can you post a link to a full example? Most likely the map-view has some css which is overriding how core-pages is trying to hide it.

**Comment by terrywarwar** [comment]
Here's a link to a working example, https://github.com/terrywarwar/core-pages-google-map-example

**Comment by jakemac53** [comment]
This is pretty weird, if you select the map-view and inspect it you can confirm that it is set to visibility: hidden, yet for some reason the map contained inside it is still visible.

I wasn't able to track down exactly why that is, but it seems like a bug on the google map library itself.

I did find a workaround, which is to simply assign a background color to the <home-view> tag, it has a higher z-index so that covers up the map. This is really just hiding the problem though.

**Comment by terrywarwar** [comment]
Yes, I noticed the visibility: hidden.  Nice workaround, I wanted to put a background color on that view anyway.

@a14n maybe able to shed some light on the issue.

**Comment by terrywarwar** [comment]
The core-animated-pages uses display: none, not visibility:hidden like core-pages. Looks like display: none in core-pages works with google maps.

**Comment by a14n** [comment]
Sorry, no idea (and I cannot reproduce the issue with https://github.com/terrywarwar/core-pages-google-map-example/commit/b51b256ff0a68649f5eeae7fe50611f48b7aa501)

**Comment by jakemac53** [comment]
@a14n I was definitely able to get a repro with that example, I only tried in dartium I wonder if you were trying the compiled version and that behaved differently?

**Comment by a14n** [comment]
I used dartium/stable .

**Comment by jakemac53** [comment]
Interesting, I am on the dev release so I wonder if that could have anything to do with it

**Comment by jakemac53** [comment]
weird..... now I can't get a repro either

**Comment by a14n** [comment]
I did try with dev channel as well. But same result. I was wondering if a `git push -f` was used.

**Comment by jakemac53** [comment]
I haven't synced since yesterday when I was able to repro though... so that is weird. The only thing I can think of is I may have updated my dev version yesterday.... so maybe it was a dartium bug? It did kind of seem that way.

**Comment by jakemac53** [comment]
@terrywarwar can you confirm if you can still repro on the latest dev release?

**Comment by terrywarwar** [comment]
I can't reproduce in latest dev version, it works.  Looks like it was a dartium bug.
