### ISSUE TITLE
core-icon demo shows check-circle but icon definition missing from core_icons.html

### ISSUE THREAD

**Issue by matthewfranglen** [dart-lang/core-elements#204]
The [polymer elements demo page for core icons](https://www.polymer-project.org/0.5/components/core-icon/demo.html) shows amongst others the _check-circle_ icon. This should be present in the core-icons.html provided by this library, however when I attempt to style a core-icon with that the icon does not appear. This icon was available in previous versions.

It also appears that the new 3d-rotation icon is missing.

**Comment by jakemac53** [comment]
We need to update to 0.5.5 which should bring this all up to date, please follow https://github.com/dart-lang/core-elements/issues/188.
