### ISSUE TITLE
custom_element_apigen doesn't have common.dart

### ISSUE THREAD

**Issue by tejainece** [dart-lang/core-elements#207]
custom_element_apigen doesn't seem to include common.dart anymore. But this file is being imported in several files in paper-elements.

**Comment by RobertMcDermot** [comment]
Here's the relevant changelog for custom_element_apigen: https://github.com/dart-lang/custom-element-apigen/blob/1c5c545daefcf4dffe628b011a1ba293f5789186/CHANGELOG.md#017

And the relevant commit: https://github.com/dart-lang/custom-element-apigen/commit/1c5c545daefcf4dffe628b011a1ba293f5789186

**Comment by jakemac53** [comment]
thanks for the report, run pub upgrade now and it should be fixed
